app/models/consultation.rb, app/models/first_name.rb, app/models/note.rb, app/models/patient.rb, app/models/treatment.rb, app/models/user.rb, db/migrate/20220830093401_add_column_to_users.rb, db/migrate/20220830094754_create_patients.rb, db/migrate/20220830095232_create_consultations.rb, db/migrate/20220830101856_create_treatments.rb, db/migrate/20220830105024_create_notes.rb, db/schema.rb, test/models/consultation_test.rb, test/models/first_name_test.rb, test/models/note_test.rb, test/models/patient_test.rb, test/models/treatment_test.rb
Création des models avec les différentes migrations. 
(sans les validates)
=> création des models

app/models/consultation.rb, app/models/first_name.rb, app/models/patient.rb, app/models/user.rb
J'ai retravaillé les models avant de commencer les validates. Il manquait des belongs_to et Has_many
=> travail sur les has_many/belongs_to

config/routes.rb
=> add the routes

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login.scss, app/assets/stylesheets/config/_fonts.scss, app/models/user.rb, app/views/pages/component.html.erb, config/routes.rb
gestion des conflit, font et login
=> Front fonts and components

app/controllers/consultations_controller.rb, app/models/treatment.rb, app/models/user.rb, app/views/consultations/index.html.rb, config/routes.rb, db/seeds.rb, test/controllers/consultations_controller_test.rb
=> finish seeds

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_input.scss, app/assets/stylesheets/components/_login.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/pages/component.html.erb
login en cours et input terminé
=> input terminé

app/controllers/consultations_controller.rb, app/views/consultations/show.html.erb
=> create the show of consultations

app/assets/images/avatar_femme.svg, app/assets/images/avatar_homme.svg, app/assets/stylesheets/components/_cards-consultation.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login.scss, app/assets/stylesheets/components/_tag_soins.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/component.html.erb
Ajout des cards patient done et wating de l'index dans la page composent
=> cards done et waiting terminées

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> homepage view ok

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_collapse.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tabs_patient.scss, app/controllers/notes_controller.rb, app/views/consultations/show.html.erb, app/views/notes/new.html.erb, app/views/pages/component.html.erb, config/routes.rb, test/controllers/notes_controller_test.rb
- Creation composants fiche patient 
- création la new note
=> components fiche patient

app/assets/stylesheets/components/_input.scss, app/controllers/consultations_controller.rb, app/models/patient.rb, app/views/consultations/new.html.erb, app/views/pages/component.html.erb
I created the new of consultations
=> New consultations

app/assets/stylesheets/components/_input.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_patients_new.scss, app/controllers/patients_controller.rb, app/views/pages/component.html.erb, app/views/patients/new.html.erb, config/initializers/simple_form_bootstrap.rb, db/migrate/20220905083452_add_gender_to_patients.rb, db/schema.rb
=> New patient

app/controllers/consultations_controller.rb, db/seeds.rb
I fixed the double apparition of favorite notes
=> solved favorites

app/views/shared/_navbar_dahlia.html.erb
Bouton Accueil => Home
Bouton Consultations => Index Consultations
=> liens dans la navbar

app/controllers/consultations_controller.rb, app/models/consultation.rb, app/views/consultations/show.html.erb
J'ai résolu le problème lié à la show des notes
=> J'ai résolu le problème lié à la show des notes

config/environments/production.rb
réglage config production pour traduction de la date
=> travail sur trad date et horraire

app/views/treatments/new.html.erb
=> Revert "margin haut + bas"

app/controllers/consultations_controller.rb, app/javascript/controllers/edit_controller.js, app/javascript/controllers/index.js, app/views/consultations/show.html.erb, config/routes.rb
FRONT - Added a button at the top of the SHOW page of a consultation. Name of the button: "Modifier la date de consultation". Style: same as "Fermer la consultation" (no extra styling)
BACK - This button does nothing for now
=> Added a button on the consultation show page to edit the consultation date

app/controllers/treatments_controller.rb, app/javascript/controllers/form_controller.js, app/views/consultations/show.html.erb, app/views/treatments/edit.html.erb, config/routes.rb
**FRONT**
_app/views/consultations/show.html.erb_
_app/views/treatments/edit.html.erb_
- Added a fontawesome edit icon next to the checkbox of each treatment on the consultation SHOW page
- Added the "d-flex align-items-center" Bootstrap classes to the parent div of checkbox and edit icon
- Added a separate EDIT view for treatments (nesting EDIT on SHOW page was buggy)
**BACK**
_config/routes.rb
app/controllers/treatments_controller.rb_
- Changed routes (added EDIT UPDATE to nested TREATMENTS)
- Added EDIT and UPDATE methods to treatments controller
=> Added icon to edit a treatment on consultation show page

app/controllers/notes_controller.rb, app/views/consultations/show.html.erb, app/views/notes/edit.html.erb, config/routes.rb
**FRONT**
Added an edit and a trash icon next to each note, with some Bootstrap padding (_to be changed later_)
Put star, edit and trash icons in a parent div with Bootstrap class "d-flex align-items-center" (_to be changed later_)
**BACK**
Added #edit, #update, #destroy routes to notes
Added #edit, #update, #destroy methods to notes controller
Created edit view for notes
=> User can edit and delete a note

Gemfile.lock, app/controllers/consultations_controller.rb, app/views/consultations/new.html.erb, app/views/consultations/show.html.erb
BACK
Lors de la création d’une consultation pouvoir associer à la consultation un infirmier de son groupe (new consultation)
=> Team consultation new

app/controllers/consultations_controller.rb, app/javascript/controllers/edit_controller.js, app/views/consultations/show.html.erb
FRONT
Ajout d'un bouton dans formulaire de l'édit d'une consultation et js pour pouvoir le faire dans la show d'une consultation 
BACK
Méthode pour assigné un autre infirmier lors de l'édit d'une consultation (controller consultation)
=> pouvoir assigné un infirmier lors de l'edit de la consultation

app/assets/stylesheets/components/_froms.scss, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Ajout du front pour l'inscription +  la barre de menu en bas sauf pour la landing et les pages de connexion et inscription 
et mis en commentaire les validates sur le first name et le phone number pour qu'un utilisateur puisse s'inscrire
=> Ajout de la barre du menu en bas et front de la page d'inscription 

app/assets/stylesheets/patient/_fiche_patient.scss, app/javascript/controllers/see_all_controller.js, app/views/patients/_consultations_patient.html.erb, app/views/patients/show.html.erb, app/views/shared/_fiche_patient.html.erb
TODO
- Globally, fix colors, fonts, sizes, measurements etc.
- Fix pictograms
- Change the navbar (front-end)
- Add an avatar picture to patients (back-end + front-end)
- Code the "Modifier les informations" link (back-end)
- Code the + button to create a consultation (back-end + front-end)
LOOM
https://www.loom.com/share/9a818c0756784a2d8f4d4c40b4e61cf8
=> More or less finished the FICHE PATIENT - front-end

app/controllers/patients_controller.rb, app/models/consultation.rb, app/models/treatment.rb, app/views/patients/_consultations_patient.html.erb, db/seeds.rb
- Deleted buggy picto images on the patient show page (in the consultations cards)
- Fixed the order and scope of consultations (we now have past consultations only, with the most recent first)
- Added past consultations to Alexandre Roux in the seeds
=> Various fixes on patient show page

app/assets/images/icones/btn-add-rose.svg
=> Ajout du bouton + avec le fond rose

app/assets/stylesheets/consultation/_show.scss, app/views/consultations/show.html.erb
Le front de la show de la consultation (qui va à peu près mais il reste des petites retouches @Paquerett 
Comme vu avec @ThomasPerez13  : 
- quand on clique sur l'infirmier, on peut modifier l'assignation de la consultation avec les autres infirmiers qui sont dans les teams (cela suppose d'avoir créé une team avant).
- Quand on clique sur la date, on peut la modifier
Ces 2 choses qui sont faites avec JS, j'ai essayé de faire ce que je pouvais en front mais j'ai pas les skills pour faire mieux. Il y aura des des petites motifs à faire mais c'est fonctionnel et ça ressemble davantage au front du visuel (avant après en photo).
=> Frontconsultation

app/assets/stylesheets/patient/_fiche_patient.scss, app/controllers/patients_controller.rb, app/views/patients/_consultations_patient.html.erb
https://www.loom.com/share/6d8dc2d0e5554999b09b3c512308d3b2
Added a Plus button to create a consultation from the Patient profile page
=> Added the PLUS button on the most ancient consultation card

app/assets/stylesheets/patient/_fiche_patient.scss, app/views/shared/_fiche_patient.html.erb
=> Added the correct pictos in the Infos personnelles section

app/assets/stylesheets/notes/_new.scss, app/views/notes/new.html.erb
La page de front améliorée pour l'ajout d'une note
=> front pour ajouter une note

app/assets/stylesheets/notes/_new.scss, app/views/notes/edit.html.erb, app/views/notes/new.html.erb
La page de front améliorée pour la modif d'une note
=> le front pour le modif note

app/assets/stylesheets/application.scss, app/assets/stylesheets/notes/_new.scss, app/assets/stylesheets/team/_index.scss, app/assets/stylesheets/team/_new.scss, app/views/notes/edit.html.erb, app/views/notes/new.html.erb, app/views/teams/new.html.erb
La page de front améliorée pour l'ajout d'une team
=> front pour l'ajout d'une team

app/assets/stylesheets/patient/_edit.scss, app/assets/stylesheets/patient/_fiche_patient.scss, app/assets/stylesheets/patient/_index.scss, app/controllers/patients_controller.rb, app/views/patients/edit.html.erb, app/views/shared/_fiche_patient.html.erb
Back : code du edit et update dans le controller patient
front : augmenter la taille de "modifier patient" et coder le édit en vue + scss
=> Editpatient

app/controllers/consultations_controller.rb
Fix a bug to create a new consultation without recurency
=> fix bug to add consultation without recurency

app/controllers/patients_controller.rb
back nurse peut voir uniquement ses patients et ceux de ses groupes
=> la liste des patients (uniquement ceux de la nurse et de ses groupes)

app/assets/stylesheets/patient/_fiche_patient.scss, app/views/patients/_consultations_patient.html.erb
Possibilité d'ajouter une consultation dans la show du patient quand il n'y en a pas encore
=> ajouter consultation show patient 

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards-consultation.scss, app/assets/stylesheets/components/_forms.scss, app/controllers/patients_controller.rb, app/models/patient.rb, app/views/consultations/new.html.erb
- Dans le model du patient, création d'une méthode de classe pour sélectionner les patient selon leurs groupe d'infirmier. Ré-utiliser cette méthode dans le controller du patient pour l'action index et dans le controller des consultations pour l'action new.
- Ajuster la disposition du formulaire new consultation pour le centrer + ajout du scroll si composant + grand que la page.
- Ajout du scroll si boucoup de patient afin de tous les afficher correctement. (Exemple en vidéo)
https://user-images.githubusercontent.com/104198121/214445434-f799385e-5993-41e8-ba8f-90f82a964e56.mp4
=> Display patient according doctor when new consultation is create

app/controllers/patients_controller.rb, app/views/patients/_consultations_patient.html.erb
affichage de toutes les consultations dans la show du patient
=> toutes les consu avec les 3 dates les plus tard en 1er

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_destroy-confirmation-modal.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/notes_controller.rb, app/controllers/treatments_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/modal_confirmation_to_destroy_controller.js, app/views/notes/edit.html.erb, app/views/shared/_destroy_confirmation_modal.html.erb, app/views/shared/_flashes.html.erb, app/views/treatments/edit.html.erb
- add style to delete note and treatment button
- add a modal to confirm if you really want to delete note or treatment
- add information message if note or treatment are well deleted
=> action destroy for treatments and notes

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_destroy-confirmation-modal.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/consultation/_show.scss, app/javascript/controllers/edit_controller.js, app/views/consultations/show.html.erb
When you click on the nurse you can modify the assigned nurse to the consultation
When you click on the date you can modify the date of the consultation
=> Consultation edit date and time and edit nurse

app/models/consultation.rb, app/models/consultation_group.rb, db/seeds.rb
- Ajout d'une consultation journalière pendant 3 mois pour les patients de Thomas
- Optimiser les seeds pour limiter la répétitions des lignes
=> Update recurrence seeds

app/assets/stylesheets/components/_destroy-confirmation-modal.scss, app/assets/stylesheets/consultation/_show.scss, app/views/consultations/show.html.erb, app/views/shared/_destroy_confirmation_modal.html.erb
Ajout d'une croix en haut à droit des différent modal:
- confirmation de la suppression d'un soins 
- confirmation de la suppression d'une note
- modification de la date d'une consultation
- modification de l'infirmier/ère d'une consultation
=> add cross on the top right corner to close different modal

app/models/treatment.rb
Back : changement nom des catégories (voir ticket) et up case de toutes les catégories de soin
=> changement de nom et upcase catégories

app/assets/stylesheets/components/_pictos_soins.scss, app/views/consultations/show.html.erb
Retour des images des soins dans new traitement et édit + consultation show
=> Les images des soins (fix) 

app/assets/stylesheets/components/_forms.scss, app/controllers/treatments_controller.rb, app/models/treatment.rb, app/models/treatment_group.rb, app/views/consultations/new.html.erb, app/views/treatments/new.html.erb, db/migrate/20230221213025_add_recurring_to_treatments.rb, db/migrate/20230221222352_create_treatment_groups.rb, db/migrate/20230221222648_add_treatment_groups_reference_to_treatments.rb, db/migrate/20230221225953_change_treatment_groups_to_treatment_group_in_treatments.rb, db/schema.rb, db/seeds.rb, test/models/treatment_group_test.rb
DB
- Création de la table "treatment_group"
- Ajout de la colonne "recurring" dans la table treatment
- Ajout de la clé étrangère"treatment_group_id" dans la table treatment
VIEW
- Afficher une checkbox pour créer une récurrence des soins pour les consultation régulière suivante
- le soin se crée pour la consultation et les suivantes
- la checkbox s'affiche seulement si la consultation est crée pour être régulière avec une fréquence
=> Create treatments with recurency

app/assets/stylesheets/patient/_fiche_patient.scss, app/views/patients/_consultations_patient.html.erb
Pouvoir voir les anciennes consultations dans la show du patient (avec afficher plus)
=> les anciennes consus dans patient

app/assets/stylesheets/components/_destroy-confirmation-modal.scss, app/assets/stylesheets/consultation/_show.scss, app/controllers/consultations_controller.rb, app/javascript/controllers/modal_confirmation_to_destroy_controller.js, app/javascript/controllers/star_controller.js, app/views/consultations/show.html.erb, config/routes.rb
- Ajout d'un icône "poubelle" pour supprimer la consultation
- Affichage modal pour confirmer la suppressioon de la consultation
- Si confirmation redirection vers la show du patient.
=> Destroy consultation

app/assets/stylesheets/components/_destroy-confirmation-modal.scss, app/assets/stylesheets/consultation/_show.scss, app/controllers/consultation_groups_controller.rb, app/controllers/consultations_controller.rb, app/controllers/treatments_controller.rb, app/javascript/controllers/modal_confirmation_to_destroy_controller.js, app/javascript/controllers/star_controller.js, app/models/consultation_group.rb, app/views/consultations/show.html.erb, app/views/notes/edit.html.erb, app/views/shared/_destroy_confirmation_modal.html.erb, app/views/treatments/edit.html.erb, config/routes.rb, test/controllers/consultation_groups_controller_test.rb
- Si la consultation est régulière afficher un bouton pour supprimer toutes les consultations concernées
- Ouverture d'une nouvelle modale pour confirmer la supression de toutes les consultations et descriptif de la fréquence ainsi que la date de fin de la récurrence
- Redirection vers la fiche patient avec message de confirmation de la suppressions des consultations règulières
=> Destroy consultation group

app/assets/stylesheets/patient/_fiche_patient.scss, app/views/patients/_consultations_patient.html.erb
dans show du patient : les consu < today seront grisées
=> Consugrisées
